language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: rtAPzTGYXzvlrnFYkGwq622CXepJ1p+fvXwuuxdBM33ocYP1yvdlzXQPeNjnix+HUHqULmd2E8AR0wDuAZCGkovusEV5Suv38gO2hnWHDGWCQv0AdIAIhBVThnRC7XxTS+tGHxtWtJOhaw+g3UlwJ48JCsOqU3vn1tALIoABvylEHoGr0fE3VmcRuUGutmO5JaszPTwevkNbs7aee+C3+iMktdN86CTGXtRLk+iSRI9Bb3SOY4tx+BdFWLnhCl2OqIe6wJltD9MdfiaPW4ztiEVfXklYDJL2OwRDcDWxTPBaKVZBq+7UFy8G6h799ALCtRcqXpWC3DINiebrXKajczqTlR9LdAAa4ElMi7s2tmkzd4ySoAxs5/prAvbKhtOgdU0MhODsWDArsmDv9z/EqDcVNJwSLErqBcc2Y8GxZ3AblpCR3Vl8dh2zq9t6dBZv8eCXZFDrYpiKNXlp1LP9gXRKssMuaKQq8YFrFCoDZx6EH87J7B2deDmZ+P1X4r3Ux+NxbrFgZHkGzDTjh7vqm7i7VeoV5XCxLQd9CN29EQuSuTM4wwUfYUIAdldSg/IjGtDQ0do9LJ56pKlJ3RybIDxUne+UYpjAuamv5T//hUtOz7MqKDMOXyLUyUBfk2yBghxsKl9iK/AStTSouGCPvXNvTdMt+z8wih54L+Sk15c=
  api_key:
    secure: RwX93uxc8DSPV+Z7DDmBWVAAXTGLiSnE61I784yGCAzi+1+JOTK/x9jYxHUMGeDAkNznZHgMOMgZvhQmCd7ij3e2FjGh/GpXyRnFy/S25jrH2OPHtmhyb+GXGqAMJYT5iM16Jfm5VDHXfx9jg8WtVde/UBmvFKKpUYWEVVy8w94+l87hQTKc1hNMgqsSumMJnW9zK1Y6XYXoQ8WpRcGYJmyO+CpqVLF7jY1Xd3X/OMFj7VxtW3kRcEm++BaLfVlOhJfFdl2YtG2eXsRlTgHz9xzAguRM1mKgWvJ3RJ8cBJv1qDtiXZsWxFlLaF2zkxvpIttlqINrZRKckduQ50RBuPSAcEHDSsoNir1/Ur6AZ2LQ8G7W9N+Umt5HMSaLK1R32FvWyunXTIfPEF+kZ6TU1sPqU+kupkhwpGc8wWJ3B7p3TqYXXB2ldXsexJ7HkjMVQpfVkwYQmjVPXPMyFzwGTV2vOYmHhNxtrAhaqSqgCRk/yC11vkvl8+s53Fba+pDwChgpseqx/kJVptFqRd1+pE1xZp0zpORBFg9sCtzkZHO4pNgZsHdHn8vdDhTocinO4Oeznil/OF7Ux2Qjk4VLRq9zOgBFh0phYHqvlbQbQjAWUgDXOWwhJMN7Y5m0u8WeDRjYKbBPMFkGEwElRlWv6U8so3tHdl53kJ/iaV+KfG4=
  on:
    tags: true
    repo: thelounge/thelounge-theme-zenburn
    branch: master
